# Generated by Django 5.0.7 on 2024-11-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('leaves_taken', models.IntegerField(default=0)),
                ('on_leave', models.BooleanField(default=False)),
            ],
        ),
    ]
